export const EVENT_SIMPLE_TABLE_ITEM_CLICK = 'EVENT_SIMPLE_TABLE_ITEM_CLICK';
export const EVENT_SIMPLE_TABLE_SKIP_BUTTON_CLICK = 'EVENT_SIMPLE_TABLE_SKIP_BUTTON_CLICK';
export const EVENT_SIMPLE_TABLE_LONG_SURVEY_CLICK = 'EVENT_SIMPLE_TABLE_LONG_SURVEY_CLICK';

export const EVENT_TOAST_MESSAGE = 'EVENT_TOAST_MESSAGE';
export const EVENT_ERROR_TOAST_MESSAGE = 'EVENT_ERROR_TOAST_MESSAGE';
export const EVENT_WARNING_TOAST_MESSAGE = 'EVENT_WARNING_TOAST_MESSAGE';
export const EVENT_LOGIN_TOAST_MESSAGE = 'EVENT_LOGIN_TOAST_MESSAGE';
